### ISSUE TITLE
Question on filtering when there should be no results. 

### ISSUE THREAD

**Issue by schneiderderek** [arillo/Backbone.Facetr#2]
Hello,

First, I wanted to mention how helpful this library has been for implementing search on a project that I am working on. I appreciate the time and effort you've put both into the library and the docs. However, I do have a question about the behavior. When you add a facet and filter by a particular value and that value doesn't match any of the items in the collection (i.e. I would expect the collection to be empty), Facetr instead does not 'empty' the collection, but leaves it untouched. Is this intended behavior? If so, is there an option that I can use to change this behavior?

Here is a screenshot to [hopefully] better illustrate what is happening:
![screenshot 2015-01-29 01 22 05](https://cloud.githubusercontent.com/assets/2245041/5953290/6c1aadac-a755-11e4-96e5-18157c24c629.png)

In this example, I would expect the call `Facetr(states).facet('name').value('y')` to empty the states collection, since there is no model that has an attribute called name with the value 'y'.

Thank you in advanced for your assistance! :)

**Comment by francesko** [comment]
Hi schneiderderek,

I just released a new version which should fix the issue. Let me know if it works for you.

Cheers

**Comment by schneiderderek** [comment]
@francesko,

I just checked out the new version and it's working great. Thanks for the fix!
