### ISSUE TITLE
Filtering incorrectly shows no results in some cases

### ISSUE THREAD

**Issue by Blasz** [arillo/Backbone.Facetr#3]
I think the fix in #2 has broken filtering in cases where a facet has been filtered to both a valid value and a non-existing value. Instead of filtering the resultset to the valid value it filters out the whole collection.

Reproduction steps below:

![image](https://cloud.githubusercontent.com/assets/2231370/8196613/d2347bde-14d0-11e5-823b-f4d123ad3557.png)

Expected behaviour: The internal operator of the `name` facet is 'or' by default and so adding a filter with a non-existing value, in this case `z`, to an already filtered collection should not change the collection resultset.

Actual behaviour: Adding a non-existing value filter to a facet always empties the collection when combined with other valid filters.

Hopefully this makes sense.

Thanks.

**Comment by francesko** [comment]
@Blasz This should be fixed, check out version 0.3.7 and let me know if it works for you.

**Comment by Blasz** [comment]
@francesko Thanks, the bug fix is working as intended thankyou.
